name: bangkok_university
description: Bangkok University Campus Navigation App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Основные зависимости для старта
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  mobile_scanner: ^3.5.0
  provider: ^6.1.1
  http: ^1.1.0
  mapbox_gl: ^0.16.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.0.0
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  camera: ^0.11.3
  permission_handler: ^10.4.4
  flutter_local_notifications: ^15.1.0
  url_launcher: ^6.1.14
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/campus_data.json
    - assets/icons/
    - assets/data/
